spring.application.name=smarthire
server.port=${PORT:8083}

spring.datasource.url=jdbc:postgresql://dpg-d74j02f5r7bs73cuf640-a.oregon-postgres.render.com:5432/smarthire_twv6?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect





spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.jwt.secret=${JWT_SECRET:ZmQxN2Y1YmQyYjVkMmQ1ZWQ2MGE4MGM4YjNlYTY5NDY2ODNkZWM1Y2RmMGU4NjQ5YjJmNGU1MDgwYjBjYjk4ZQ==}
app.jwt.access-token-expiration=86400000
app.file.upload-dir=${FILE_UPLOAD_DIR:uploads/resumes}
app.mail.from=${MAIL_FROM:aakashsrivastava2151@gmail.com}
app.frontend.base-url=${FRONTEND_BASE_URL:https://smarthire001.netlify.app}
app.video.base-url=${VIDEO_BASE_URL:https://meet.jit.si}
app.video.provider=${VIDEO_PROVIDER:JITSI}






ml.api.base-url=${ML_API_BASE_URL:https://skill-detection-1.onrender.com}
ml.api.resume-analyze-path=${ML_API_RESUME_ANALYZE_PATH:/analyze_resume}
ml.api.timeout-millis=${ML_API_TIMEOUT_MILLIS:30000}
ml.api.enabled=${ML_API_ENABLED:true}
ml.api.api-key=
ml.api.api-key-header-name=x-api-key

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.smarthire=INFO

app.auth.resend-otp-api-key=${RESEND_OTP_API_KEY:smarthire-resend-otp-key}

ml.api.spam-base-url=${ML_API_SPAM_BASE_URL:https://spam-yege.onrender.com}
ml.api.spam-predict-path=${ML_API_SPAM_PREDICT_PATH:/predict}



app.ai.gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta}
app.ai.gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
app.ai.gemini.api-key=${GEMINI_API_KEY}
app.ai.gemini.api-key-header-name=${GEMINI_API_KEY_HEADER_NAME:x-goog-api-key}

ml.api.skill-videos-base-url=${ML_API_SKILL_VIDEOS_BASE_URL:https://chatbot-6bs1.onrender.com}
ml.api.skill-videos-path=${ML_API_SKILL_VIDEOS_PATH:/videos}



